# Libraries

In [43]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import os

# Import Data

In [55]:
steam_game_3 = pd.read_csv('steam_game_cleaned.csv')

In [56]:
steam_game_3.columns

Index(['name', 'release_date', 'price', 'dlc_count', 'detailed_description',
       'about_the_game', 'short_description', 'windows', 'mac', 'linux',
       'metacritic_score', 'achievements', 'recommendations',
       'supported_languages', 'full_audio_languages', 'developers',
       'publishers', 'categories', 'genres', 'positive', 'negative',
       'estimated_owners', 'average_playtime_forever',
       'average_playtime_2weeks', 'median_playtime_forever',
       'median_playtime_2weeks', 'peak_ccu', 'tags', 'sup_lang_num',
       'full_audio_num', 'extra_lang_supported', 'dev_num'],
      dtype='object')

# Modeling

## Price Distribution

In [110]:
steam_game_3['price_bracket'] = pd.cut(steam_game_3['price'], bins=[0, 5, 10, 20, 30, 50, 100, 1000], labels=['1-5', '5-10', '10-20', '20-30', '30-50', '50-100', '100+'])
steam_game_3['genres_mod'] = steam_game_3['genres'].str.replace('[', '').str.replace(']', '').str.replace("'", '').str.split(', ')

In [111]:
price_data = steam_game_3.explode('genres_mod')
price_data = price_data[~(price_data['genres_mod'].isin(['', 'Movie', 'Free to Play']))]
price_data = price_data[price_data['price'] > 0]

In [129]:
price_data[price_data['price_bracket'] == '50-100'].drop_duplicates(subset='name').sort_values('price', ascending=True).shape

(361, 34)

In [131]:
price_data2 = price_data.groupby(['price_bracket', 'genres_mod'], observed=False).size().unstack()
price_data2

genres_mod,Accounting,Action,Adventure,Animation & Modeling,Audio Production,Casual,Design & Illustration,Early Access,Education,Game Development,...,Racing,Sexual Content,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Violent,Web Publishing
price_bracket,,,,,,,,,,,,,,,,,,,,,
1-5,2,8002,7348,50,20,9373,62,1297,28,12,...,800,51,3575,14,807,3300,144,23,220,8
5-10,1,4482,4603,23,13,3881,47,1216,41,20,...,384,20,2335,17,482,2328,76,15,107,7
10-20,4,4115,4190,43,22,2176,67,1731,29,36,...,306,11,2338,25,461,2099,74,20,56,15
20-30,0,844,832,13,13,319,16,317,17,9,...,86,1,618,10,136,550,23,10,6,8
30-50,0,363,327,15,11,96,26,59,10,7,...,59,1,244,7,94,216,25,13,1,5
50-100,0,147,79,24,15,33,35,9,15,9,...,22,0,65,13,27,50,27,20,0,11
100+,0,6,3,11,2,7,6,4,0,7,...,1,0,5,0,1,3,0,7,0,0

## Market Patterns